version: '3.9'

services:
  db:
    image: postgres:15
    container_name: stress-db
    restart: always
    environment:
      POSTGRES_DB: stress_assessment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: littleeov
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: stress-backend
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:littleeov@db:5432/stress_assessment_db
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: stress-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres-data:
